### PR TITLE
Adding functionality for enumerating trusted domains

### PR DESCRIPTION
**Pull request by jgoosey**
Saw this https://github.com/garrettfoster13/pre2k/issues/7 and ran into the same issue on a client engagement. Tested the auth functionality and it works as intended. Let me know if there's any issue as it's my first PR

### CODE REVIEW

**Comment by garrettfoster13** [comment]
NIce, skimmed through and its how I would've done it. Thanks for taking care of my laziness.

**Comment by jgoosey** [comment]
I referenced sccmhunter while adding it in so it's basically you by proxy lol

**Comment by garrettfoster13** [comment]
@jgoosey can you take a look at #18?

**Comment by jgoosey** [comment]
Yupp! Modified the wrong line in pre_2k.py. Fixing now

**Pull request merged**
